name: Run automated tests

on: [push, pull_request]
  
jobs:
  run-tests:
 
    runs-on: ubuntu-20.04
    
    container:
      image: lubo1994/pv-hawk:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install tools
        run: |
          rm /etc/apt/sources.list.d/cuda.list
          rm /etc/apt/sources.list.d/nvidia-ml.list
          apt-get update -y
          apt-get install -y wget
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==4.0.1 coverage==6.2
        
      - name: Download Mask R-CNN weights
        run: |
          mkdir -p /pvextractor/extractor/segmentation/Mask_RCNN/
          wget https://github.com/LukasBommes/PV-Hawk/releases/download/v1.0.0/mask_rcnn_pv_modules_0120.h5 -O /pvextractor/extractor/segmentation/Mask_RCNN/mask_rcnn_pv_modules_0120.h5
          
      #- name: Lint with flake8
      #  run: |
      #    # stop if there are syntax errors or undefined names
      #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #    # exit-zero treats all errors as warnings, the GitHub editor is 127 chars wide
      #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
      - name: Test with unittest
        run: |
          python -m unittest tests/**/test_*.py
          
      #- name: Test coverage analysis
      #  run: |
      #    coverage run --source=. --branch -m unittest tests/**/test_*.py
      #    coverage report -m
      #    # create html coverage report in htmlcov
      #    coverage html
